const products = [
  {
    _id: "1",
    name: "迷你一辑 I AM",
    image: "/images/I-AM.jpg",
    description:
      "《I am》是(G)I-DLE首张迷你专辑，于2018年5月2日推出，主打歌曲为〈LATATA〉,并于同日举行出道Showcase正式出道。",
    brand: "(G)I-DLE",
    category: "音乐唱片",
    price: 502,
    countInStock: 2018,
    rating: 5.0,
    numReviews: 100,
  },
  {
    _id: "2",
    name: "单曲专辑 DUMDi DUMDi",
    image: "/images/DUMDi-DUMDi.jpg",
    description:
      "《DUMDi DUMDi》是(G)I-DLE首张单曲专辑，于2020年8月3日推出。在荒漠中取景的影片洋溢着异国风情，散发出与(G)I-DLE近期作品截然不同的魅力。",
    brand: "(G)I-DLE",
    category: "音乐唱片",
    price: 83,
    countInStock: 803,
    rating: 4.7,
    numReviews: 90,
  },
  {
    _id: "3",
    name: "正规一辑 I NEVER DIE",
    image: "/images/I-NEVER-DIE.jpg",
    description:
      "I NEVER DIE》是(G)I-DLE的首张正规专辑，于2022年3月14日推出，主打歌为〈TOMBOY〉，并且首次以五人体制回归",
    brand: "(G)I-DLE",
    category: "音乐唱片",
    price: 136,
    countInStock: 314,
    rating: 4.9,
    numReviews: 37,
  },
  {
    _id: "4",
    name: "迷你五辑 I LOVE",
    image: "/images/I-LOVE.jpg",
    description:
      "《I love》是(G)I-DLE的第五张韩语迷你专辑，由Cube娱乐制作，Kakao娱乐发行，专辑于2022年10月17日推出，主打曲为〈Nxde〉。",
    brand: "(G)I-DLE",
    category: "音乐唱片",
    price: 130,
    countInStock: 107,
    rating: 4.8,
    numReviews: 75,
  },
  {
    _id: "5",
    name: "迷你六辑 I FEEL",
    image: "/images/I-FEEL.jpg",
    description:
      "《I feel》是(G)I-DLE的第六张韩语迷你专辑，由Cube娱乐制作并于2023年5月15日发行，5月10日韩国时间0点整公开先行曲〈Allergy〉，于15日下午发布主打曲〈Queencard〉。",
    brand: "(G)I-DLE",
    category: "音乐唱片",
    price: 120,
    countInStock: 515,
    rating: 4.6,
    numReviews: 110,
  },
  {
    _id: "6",
    name: "英语迷你专辑 HEAT",
    image: "/images/HEAT.jpg",
    description:
      "《HEAT》是(G)I-DLE的首张英语迷你专辑，由Cube娱乐、88rising制作并于2023年10月6日发行，7月13日北美东部时间下午8时公开先行曲〈I DO〉[1][2][3]，主打曲为〈I Want That〉。",
    brand: "(G)I-DLE",
    category: "音乐唱片",
    price: 78,
    countInStock: 1006,
    rating: 3.8,
    numReviews: 2023,
  },
  {
    _id: "7",
    name: "正规二辑 2(SECOND)",
    image: "/images/2(SECOND).jpg",
    description:
      "《2》是(G)I-DLE的第二张韩语正规专辑，由Cube娱乐制作并于2024年1月29日发行，主打曲为〈Super Lady〉，一共斥资11亿韩圆制作。",
    brand: "(G)I-DLE",
    category: "音乐唱片",
    price: 88,
    countInStock: 129,
    rating: 4.5,
    numReviews: 131,
  },
  {
    _id: "8",
    name: "迷你一辑 MY（曺薇娟）",
    image: "/images/MY.jpg",
    description:
      "《MY》是(G)I-DLE主唱薇娟作为Solo出道的首张迷你专辑，于2022年4月27日推出，主打歌为〈Drive〉。",
    brand: "曺薇娟",
    category: "音乐唱片",
    price: 427,
    countInStock: 0,
    rating: 4.7,
    numReviews: 37,
  },
  {
    _id: "9",
    name: "迷你一辑 Windy(田小娟）",
    image: "/images/Windy.jpg",
    description:
      "《Windy》是(G)I-DLE队长小娟作为(G)I-DLE成员Solo出道的首张迷你专辑，于2021年7月5日推出，主打歌为〈BEAM BEAM〉。",
    brand: "田小娟",
    category: "音乐唱片",
    price: 337,
    countInStock: 1,
    rating: 4.3,
    numReviews: 75,
  },
  {
    _id: "10",
    name: "迷你一辑 Yuq1（宋雨琦）",
    image: "/images/Yuq1.jpg",
    description:
      "《MY》是(G)I-DLE中国籍成员雨琦作为Solo出道的首张迷你专辑，于2024年4月23日推出，主打歌为〈FREAK〉。",
    brand: "宋雨琦",
    category: "音乐唱片",
    price: 70,
    countInStock: 23,
    rating: 4.5,
    numReviews: 423,
  },
];

export default products;
